[package]
name = "libpaprika"
version = "0.2.0"
authors = ["Moritz Ulrich <moritz@tarn-vedra.de>"]
edition = "2018"
license = "MIT"
description = "A library to read and generate Paprika recipe files and recipe collections."
repository = "https://github.com/the-kenny/libpaprika"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.3"
libflate = "0.1.27"
serde_derive = "1.0.104"
serde = "1.0.104"
serde_json = "1.0.44"
failure = "0.1.6"
